export interface Address {
  addressId?: string;       // generated by DB
  customerId: string;       // foreign key to Customer.customerId
  addressLine1: string;
  addressLine2?: string;
  city?: string;
  state: string;
  postcode: string;
  country?: string;
  createdAt?: string;
  updatedAt?: string;
}
